### ISSUE TITLE
Variable expansion not working

### ISSUE THREAD

**Issue by brettinternet** [toddbluhm/env-cmd#117]
Thank you for submitting the latest release (https://github.com/toddbluhm/env-cmd/issues/112).

However, I'm not able to replicate variable expansion in an NPM script. Please see my simple example in [this demo repo](https://github.com/brettinternet/env-cmd-expansion).

Node Version: `13.7.0`
Npm Version: `6.13.6`
OS: Linux
Package Version: `10.1.0`

Perhaps I am missing something about how `env-cmd` stringifies the arguments to be parsed in [expand-envs.ts](https://github.com/toddbluhm/env-cmd/blob/master/src/expand-envs.ts)?

**Comment by toddbluhm** [comment]
I have found the issue. You need to escape the `$` so instead of `$TEST` it becomes `\$TEST` (or in `package.json` `\\$TEST` to create a literal `\` character). 

Also the `&& echo "var: \$TEST"` will execute as a separate command outside of the `env-cmd` call, so it will never get replaced. 

So to make your full `npm start` script work, it should look like this (npm automatically adds `./node_module/.bin` to the `PATH`):
`"start": "env-cmd -x node index.js input=\\$TEST && env-cmd -x echo \"var: \\$TEST\""`

I will update the docs to reflect this finding. I may consider changing to something like `#TEST` instead as the escaping might get confusing, but at this point, I will just see where the community wants this feature to go.

The reason I did not encounter this issue is that my test cases used `--user=$USER` in which `$USER` was already defined in my environment 🤦‍♂ I have updated my test examples to use a different environment variable using the `\\$VAR` escape method.

**Comment by brettinternet** [comment]
Great catch, thank you! @toddbluhm 

And thank you for updating the documentation.
