### ISSUE TITLE
# issue

### ISSUE THREAD

**Issue by casoetan** [toddbluhm/env-cmd#12]
Hey. Nice project.

Passwords with # do not work, event when quoted. You may want to look into that

**Comment by toddbluhm** [comment]
Hey thanks for the heads up. I had test cases for this specific case, but they must not be working or something like that. I will take a look.

**Comment by toddbluhm** [comment]
Alright, so I had some trouble with the regex in determining between what is an inline comment and what is actually a valid env value. 

So I opted to go with using double quotes around any env value the uses the `#`. So now, you should be able to just do `ENV="#somevalue"` and it will work. If you want to include double quotes in your env value, then just double the number of double quotes. `ENV=""some value surrounded in double quotes""`. 

Here is the PR for that fix: https://github.com/toddbluhm/env-cmd/pull/14 If you could check it out and see if it fixes your issue, then I will merge it in.

**Comment by toddbluhm** [comment]
Just published 4.0 which should fix this issue. Please re-open if its still not working.

**Comment by casoetan** [comment]
Doesn't yet work for me. Can you check the strip comments regex as well?

**Comment by toddbluhm** [comment]
Yeah I found another case 😦  I will keep you updated on my progress. Should hopefully have it resolved sometime tomorrow. Sorry about this.

**Comment by toddbluhm** [comment]
Quick update, this fix is going to take a little while. Regex just won't cut it. The challenge is getting the js flavor of regex to work with my inline comments, double quotes, and # sign usage. I am working on a custom parser as we speak that should solve all of theses issues, but not sure when it will be done. It will probably be open sourced as a different github project and then just incorporated back into this project. 

The current intermediate solution for the time being would be to just use a `.json` file for your env config or a `.env-cmdrc` file instead of the custom env file format that is currently supported. I know this is probably not the answer you want, but its the best I have right now. Rest assured I am committed to making the env file solution work, it will just take a bit more time.

**Comment by toddbluhm** [comment]
Another Update: If using a `.json` file or `.env-cmdrc` is not desirable, I found a weird solution that worked in my testing. If you simply add an inline comment to whatever line has the `#` symbol in its value, it should work with the current `4.x` version.  

So for example this `ENV1="some#value"` would become `ENV1="some#value" #inline comment`. Weirdly enough the above fix works in the test cases. Its why I didn't catch this earlier, because all my test cases had either inline comments or no `#` in the value.

**Comment by toddbluhm** [comment]
Hey a quick updated on this. I have not forgotten about, I have just been super busy with two tech startups and a day job. I am still working on the parser and hope to be able to get back to spending some time on it soon enough. I am still determined to get this resolved.

**Comment by toddbluhm** [comment]
I had been thinking about this for a while now and while I would love the opportunity to spend time on a parser, I think its just over kill. I have decided instead to simplify the lib and be a bit more opinionated with it. You will find my decided fix for this comment issue in this PR. It will be released shortly as 5.0 with major breaking changes. Please see the PR or change log for those breaking changes.

PR: https://github.com/toddbluhm/env-cmd/pull/19

**Comment by toddbluhm** [comment]
`5.0` is now live. Feel free to reopen with any follow up questions or bugs you might find.

**Comment by fraction01** [comment]
@toddbluhm It doesn't work with the latest version (10.1.0)
