### ISSUE TITLE
Reloading Environment Variable of Running Application

### ISSUE THREAD

**Issue by tbhaxor** [toddbluhm/env-cmd#131]
My .env file
```
ACCESS_ID=xxxxxx
```

I have started the node server with `env-cmd node server.js`

After that I have updated the ACCESS_ID &rarr; `yyyyyy`

Now i want to update these variables without exiting the server.

**Comment by toddbluhm** [comment]
I'm not sure this is even possible. The ability to dynamically change `process.env` from outside the process without introducing external code into the existing system.

Other similar environment packages get away with this because they require you to import their package into your existing app. `env-cmd` is different in that you only need `env-cmd` to run your app, you do not need to import it. Instead, this package encourages you to use the native `process.env` for fetching environment variables.

Great suggestion, just not possible as far as I know.

One thing that is possible is detecting changes to a `.env` file and then restarting the command with a new environment, but honestly, that is way too much work for this package. Most environmental variables do not (and should not) change frequently enough to warrant auto-restarting behavior.

PRs are always welcome of course.

**Comment by tbhaxor** [comment]
@toddbluhm will `pm2 reload` work in this case?

**Comment by tbhaxor** [comment]
Anyhow can i use it with `pm2` and then in pm2 i can use `pm2 reload`?

**Comment by tbhaxor** [comment]
Wait what? killing and restarting, why are you changing the logic of this env-cmd, see if this could be integrated with pm2

**Comment by toddbluhm** [comment]
Not really sure what you are trying to do. If you want to provide env vars and are using `pm2`, perhaps you should try using pm2s native env var integration via an [ecosystem file](https://pm2.keymetrics.io/docs/usage/pm2-doc-single-page/#ecosystem-file) That would certainly solve your issue.

If you still want to use `env-cmd`, best I can tell, you will still need to create an `ecosystem` file and inside use the `interpreter` option and point that to `env-cmd`, then provide whatever `env-cmd` args you want in the `interpreter_args` field and then as the last argument in that field make it `node`.  Then set the `script` field to point to your main startup script `index.js`.  That might work, or some combination like that.
