### ISSUE TITLE
process is not defined

### ISSUE THREAD

**Issue by RafMazza** [toddbluhm/env-cmd#337]
Hi,
I have two  . env files, one for dev and one for prod.
In package.json I have add:
```
"scripts": {
    "start": "env-cmd -f ./environments/.dev.env yarn start:dev",
    "start:dev": "set PORT=4200 && react-scripts start",
  },
```

But in the browser console, I have this error message:
![image](https://user-images.githubusercontent.com/93984877/149539198-c804c57e-e1ae-428e-b2b4-5a988f907f94.png)

**Comment by fgira** [comment]
Hi @RafMazza,

If think your problem is the same as : [process is not defined](https://stackoverflow.com/questions/70368760/react-uncaught-referenceerror-process-is-not-defined).

I have upgrade to react-script 5.0.0 and it solved the problem.

If you want all details and all solutions of this problem see [this](https://github.com/facebook/create-react-app/issues/11773)

**Comment by gyanverma2** [comment]
If you are installing react-script .. u dont have to install env-cmd.

**Comment by k-yle** [comment]
Hey, this error is coming from create-react-app, not env-cmd. I would joining the discussion at https://github.com/facebook/create-react-app/issues/11773
