### ISSUE TITLE
Env files should have the possibility to import another env file

### ISSUE THREAD

**Issue by corebreaker** [toddbluhm/env-cmd#41]
For example, in this _package.json_:
```javascript
{
···
  "scripts": {
    "mycmd-1": "env-cmd ./env1 The-command",
    "mycmd-2": "env-cmd ./env2 The-command"
  },
···
}
```

Then, the 2 env files:
- _./env1_:
```
COMMON=123
```

- _./env2_:
```
COMMON=123
SPECIFIC=abc
```

The common variable `COMMON` have to modified in the 2 files.
With an import of `env1` into `env2`, the common variable must just be modified in the _./env1_ env file.

This could be declared in _./env2_ like that:
```
@import=./env1
SPECIFIC=abc
```

**Comment by toddbluhm** [comment]
Thanks for this suggestion! 

At this time feel like it will overly complicate the utility too much. I like that current env files are extremely simple. A lib like this is successful and useful because it's simple and remains simple. I feel like it might already be too complicated and this would make things even more complicated. If you really do have multiple env file needs, use the `.rc` file to select the different environments.

**Comment by corebreaker** [comment]
Ok no problem, i'll fork it and i'll add the functionnality that i need.
