### ISSUE TITLE
Minimum node version support

### ISSUE THREAD

**Issue by cowchimp** [toddbluhm/env-cmd#45]
Hi.
The `engines` property in the package.json says that node version >= 4.0 is supported.
Will it really work with node versions < 6.0? (don't support `let`, etc.)

Thanks.

**Comment by toddbluhm** [comment]
Hey @cowchimp good question, so according to https://node.green/ node v4 does support `const/let` in strict mode.

I also run my test suite against various node versions including v4: https://travis-ci.org/toddbluhm/env-cmd

So with my tests all passing on node v4, I can only assume it all works. I have never had anyone tell me otherwise. Are you telling me from experience it does not work on node v4? If so, I would like to know so more information about whats happening in your case.

**Comment by toddbluhm** [comment]
Since no response, I am closing this. Please reopen if things change.
