### ISSUE TITLE
Fail when no fallback provided

### ISSUE THREAD

**Issue by mustafawm** [toddbluhm/env-cmd#59]
Hello,

Should it fail when no `--fallback` option is provided? 

I have the following 
```
// package.json
"build:preprod": "env-cmd ./config/.env.preprod webpack --config webpack/webpack.prod.js",
```
It'd be helpful if it failed when `./config/.env.preprod` is not found.

**Comment by toddbluhm** [comment]
This has been implemented in the new `9.0.0` release 🎉

**Comment by mustafawm** [comment]
Just updated to v9, one thing I ran into is passing args to the command that  `env-cmd` runs

Before
```
"start": "env-cmd ./config/.env.dev webpack-dev-server --config webpack.dev.js",
```
After
```
"start": "env-cmd -f ./config/.env.dev webpack-dev-server -- --config webpack.dev.js",
```
_Notice the extra `--` I had to pass to webpack_

It makes sense now that `env-cmd` is reading first level flags we need to tell `--`, maybe we can add an example to the readme section?

**Comment by toddbluhm** [comment]
You have found a good bug. My intent was to not have to use `--`, but somehow my tests missed that. I have fixed my tests to catch the error, now I just need to fix the bug. Thank you so much for catching this so quickly!

**Comment by mustafawm** [comment]
Glad I could be of help.

**Comment by toddbluhm** [comment]
`9.0.1` has been published which should hopefully fix this issue 🎉

**Comment by mustafawm** [comment]
Nice!
- How long do I have to wait for it to become available? (`npm install env-cmd@9.0.1` is resulting in npm ERR! notarget No matching version found for env-cmd@9.0.1)
- I'm not very familiar with semver but should it have been 9.1.0 instead (since it's a potential breakage change)?

**Comment by toddbluhm** [comment]
Odd, I was able to download and install it immediately after publishing, though I did have to specify it in the install `npm i env-cmd@9.0.1`

Yes and no about the semver thing. Technically it maybe should have been `10.0.0` since the change is not backwards compatible, but if you look at my note in the changelog, I justify the non-major version number change because `—` was undocumented and unintended functionality. Think of it like using a private API of a library. No semver major/minor version is required for changing a private api since it’s undocumented and not intended for public use. `—` was not intended for public use and it was definitely undocumented. (I didn’t even know about it!)

**Comment by mustafawm** [comment]
I will try to install again in a few hours 

hmmm..makes sense. Thanks for the explanation

**Comment by mustafawm** [comment]
Can confirm, issue has been resolved in 9.0.1. `--` no longer needed to pass args

**Comment by toddbluhm** [comment]
Great to hear! If you come across any other issues, let me know so I can get them resolved. I figured with such a large rewrite there would be issues, but hopefully that was the only one. I appreciate you reporting this issue and helping me resolve it too 😄

**Comment by mustafawm** [comment]
Moving to production soon so 🤞this was the only 🐛
It's a very useful 📦 I'm more than happy to help.
