### ISSUE TITLE
.envrc file?

### ISSUE THREAD

**Issue by jennasalau** [toddbluhm/env-cmd#7]
Hey just wanted to say cool project! Thanks.

This is more of a feature request than an issue, but it seems this is using a pattern of multiple `.env` files. I think this is cool but in node land my root folder is filling up with cruft.

What I would love for this project is to have just the one `.envrc` file in my root that has multiple configurations inside (preferably in json).

ie (.envrc)

```
{
    "debug": {
         "NODE_ENV": "development"
    },
    "release": {
        "NODE_ENV": "production"
    }
}
```

Then this could allow me to define the variables in a npm script like this:

(package.json)

```
"scripts": {
    "build": "env-cmd release webpack",
    "watch": "env-cmd debug webpack --watch"
}
```

What do you think?

And thanks again for sharing your project.
Jenna

**Comment by toddbluhm** [comment]
Hey Jenna,
This is a great idea! I would certainly be interested in doing something like this. I am wondering if maybe this would solve the same situation we are trying to solve with PR #6. I see if this will solve the same use case. In the mean time, a PR is welcome...or I can try to get around to it when I have some time.

**Comment by laggingreflex** [comment]
I too would like to see this functionality but separate from the multiple env file support. One might use either of these methods to achieve similar things but fundamentally they're very different, quite the opposite in fact since this one is an effort to keep only single .envrc whereas multiple env file support is just that. I would much rather see both than either-or, and let the user decide. For context, my use case was that I was actually using the same `.env` files in docker-compose and in my node app and wanted to maintain a format that works in both.

**Comment by laggingreflex** [comment]
Some thoughts/issues with this that I think need to be addressed:

Currently `env-cmd release webpack` assumes that `release` is an .env file. To maintain compatibility it should be aware of that `.envrc` file's presence. It should probably enter an "envrc" mode in this case? 

Is `.envrc` file always json?

In the original example there's "debug" and "release" as top level keys, would env variables **only** be loaded from second level keys? If it doesn't create ambiguity, or if it could be solved, how about having variables in top level that could actually be *merged* with "debug" or "release"? Maybe "debug" or "release", being env "selectors" should be differentiated with a special identifier, like `"#debug" : {...}`

**Comment by toddbluhm** [comment]
@laggingreflex Yeah, I definitely see how they are different, just making sure the merge files was still needed. The `envrc` idea is extremely appealing to me. And as you said, one of the first things we would need to do, is on `env-cmd` start looking for the `.envrc` file and move in to an `envrc` mode to go from there.

I think second layer keys would be the way too go. If people want just a first layer, we already support that with regular env files in json, and then soon with merging as well. So the `envrc` file will be more for advanced/customized usage, and copy the format above in the given example. 

I will look into getting started on the `envrc` idea soon. @jennasalau you care to give it a shot first with a PR, or otherwise I can do it sometime soon?

**Comment by jennasalau** [comment]
Ohhh I would love to, but I'm a bit time poor at the moment.. If there is no movement on this on a month or so I can have a go then :)

**Comment by toddbluhm** [comment]
Okay sounds good. I will see if I can find some free time within the next month to get a start on it as well. I just started a new job, so my time is gone right now too...but hopefully within the next week or two things will calm down a bit more for me.

**Comment by toddbluhm** [comment]
Added support for this in [3.0.0](https://github.com/toddbluhm/env-cmd/commit/f37249e467106a5f5f480701b2fbb9a440949d53). It uses a `.env-cmdrc` file. I chose this name because I did a quick google search and found other utilities using `.envrc` and I did not want to cause possible collision with other tools a developer might be using. If people really want `.envrc` support please feel free to voice your opinion and I am certainly willing to reconsider adding it.
