### ISSUE TITLE
migration guide 9->10

### ISSUE THREAD

**Issue by piotr-s-brainhub** [toddbluhm/env-cmd#89]
Could you publish a guide showing how to upgrade from `env-cmd@9` to `env-cmd@10`?

**Comment by toddbluhm** [comment]
There should be no guide necessary. The only breaking change was typescript targeting es2017 instead of es2015. Node v8 (which is already the minimum required version) supports all es2017 features used so that should be a non-issue already. Are you experiencing an issue with `env-cmd@10`? There is an issue with `10.0.0` but that is why `10.0.1` was released almost immediately thereafter. If you are using `10.0.0` try upgrading to `10.0.1` and see if that resolves your issue.

**Comment by piotr-s-brainhub** [comment]
Thanks. It seems to work fine but I wanted to ensure nothing is neglected.
